### PR TITLE
Make derive(NoUninit) have the same constraints as Pod

### LINKED ISSUE #340: derive(NoUninit) on #[repr(transparent)] type with generic parameter?
I would like to have:
```
#[derive(NoUninit)]
#[repr(transparent)]
struct Wrapper<T>(T);
```
which seems like it should be sound if `T: NoUninit`. However it currently fails with:

```
error: NoUninit cannot be derived for structs containing generic parameters because the padding requirements can't be verified for generic structs
```

This does work for `Pod`.

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=518adfa01c2c70d7a7a31e28bc356247

### PR DESCRIPTION
**Pull request by jsgf**
Derive is allowed for generic types if they are `repr(transparent)` or `packed(1)`.

Also fixes the `completly_packed` typo because I didn't want to copy it and I didn't want the cases to be inconsistent.

Fixes #340

### CODE REVIEW

File: derive/src/traits.rs [hunk 1]
```diff
@@ -257,14 +258,26 @@ impl Derivable for NoUninit {
   fn asserts(
     input: &DeriveInput, crate_name: &TokenStream,
   ) -> Result<TokenStream> {
-    if !input.generics.params.is_empty() {
-      bail!("NoUninit cannot be derived for structs containing generic parameters because the padding requirements can't be verified for generic structs");
+    let repr = get_repr(&input.attrs)?;
+
+    let completely_packed =
```
Comment (fu5ha) [inline derive/src/traits.rs]: `packed_or_transparent` here as well

**Review by fu5ha — CHANGES_REQUESTED** [review]
Just a few nits, otherwise I think this is a good change. Thanks :)

**Comment by Lokathor** [comment]
@fu5ha want to do a final check?

**Review by fu5ha — APPROVED** [review]
